### ISSUE TITLE
assistance to validate camera setup

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#15]
Please consider providing some assistance to validate the camera setup.

For example reporting the numbers (percentage) of frames in a session where a QR code was 1) expected and 2) decoded.
This would be independent of whether the contents of the QR code were what is actually required by the test.

**Comment by jpiesing** [comment]
Also can the QR code detection libraries report anything other than yes or no - e.g. QR code found but error detection / correction failed?

**Comment by yanj-github** [comment]
Thanks Jon, we will look into this. I think we will be able to do somthing about this.

**Comment by andyburras** [comment]
@jpiesing 
The QR code libraries only give a list of the QR codes successfully decoded on an individual camera recording frame.

We could however, add documentation to the setup instructions recommending that when first installed, the user first run a specific test e.g. sequential track playback for AVC content. After running Observation Framework, then examine the "Every sample shall be rendered" result in Test Runner. If large numbers of mezzanine QR codes are missing then this will report "too many missing frames, reporting truncated. Total of missing frames is XXX." The tester can be instrcuted if this is high to manually examine the recording to establish whether there are issues with the displayed QR codes.

We will also be implementing the change for https://github.com/cta-wave/device-observation-framework/issues/10 which will terminate a session's processing if the number of missing frames exceeds a configurable threshold. So the tester will not have to wait for all the O.F. processing to complete.

**Comment by jpiesing** [comment]
> The QR code libraries only give a list of the QR codes successfully decoded on an individual camera recording frame.

@andyburras But should at least one QR code be successfully decoded for every frame even if it's the same as the previous one?

**Comment by andyburras** [comment]
`But should at least one QR code be successfully decoded for every frame even if it's the same as the previous one?`

It's not guaranteed. The way device displays appear to work, as a QR code is displayed it "fades up" from black to full brightness then "fades down" again. So it can happen that we get camera capture frames where the previous QR code has "faded down" and the next QR code is still "fading up", and neither are at levels that are decodable. This is why we capture at 120fps to guarantee that we will have at least one camera frame where a given QR code is decodable.

However, the change we're currently making for https://github.com/cta-wave/device-observation-framework/issues/10 should help this. If more than the threshold QR codes are missing (which is configurable) then the Observation session will be terminated, an ERROR result posted to the TestRunner, and the error message also printed on the Observation Framework console. So this will indicate that something is very wrong, e.g. in the camera setup, the TestRunner/test content, or the device's playback capabilities.

To do anything more sophisticated would effectively be a new Observation that would run after the QR code extraction, which would have to filter out all the camera frames that we expect to not have a mezzanine code i.e. before and between each test in a session, then analyse the remainder applying some percentage threshold.
Even then I am struggling to think how a tester would determine where the issue lies without doing a manual check of the recorded content.

**Comment by jpiesing** [comment]
What I had in mind was a simple running counter of the number of the number of frames where a QR code was successfully extracted vs either the number of frames where a QR code was not successfully extracted or the total number of frames.

**Comment by yanj-github** [comment]
We are adding some example videos and images to help getting clear recordings.

**Comment by yanj-github** [comment]
The ppt file is now avalible to download and the link is posted on readme.

**Comment by jpiesing** [comment]
Thanks for this. The PPT looks good to me except for afew small details;
 - the trailing cable in slide 7 is not at all obvious. Perhaps you might do a 2nd version of the slide with the cable highlighted. The same applies (to a less extent) for the cursor in slide 8.
- slides 18 and 19 talk about "pre-test QR code" and "end test QR code" being missing. It might be good to have captures showing what you are referring to.
- 
@cta-source What PPT template should be used for this? Should it be a CTA one?

**Comment by yanj-github** [comment]
@jpiesing 
https://dash-large-files.akamaized.net/WAVE/assets/How-to-take-clear-recordings-v2.pptx.zip 
Is the new link to the updated ppt file. 
All you commenets are addressed.

**Comment by jpiesing** [comment]
I'm OK with this version.
