### ISSUE TITLE
default values for tolerances 

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-observation-framework#17]
Currently the default values for missing frame tolerances are as follows:
start_frame_num_tolerance = 1
end_frame_num_tolerance = 0
mid_frame_num_tolerance = 0 

However, there are many frames missing on the start and 1-2 missing frames detected in the middle. 
e.g:
First frame found is 6, expected to start from 1. First frame number tolerance is 1. Last frame found is 3599, expected to end at 3600. Last frame number tolerance is 0. Mid frame number tolerance is 0. Frame 17 is missing.

What should be a suggested default values for these tolerances please?

**Comment by yanj-github** [comment]
Missing frames from biginning is a FAIL:
https://github.com/cta-wave/dpctf-tests/issues/18#issuecomment-848587730

**Comment by jpiesing** [comment]
> First frame found is 6, expected to start from 1.
> First frame number tolerance is 1.

This should be a fail. The green frame at the start needs to be visible. That's why there's a green frame on the start, to make it clear to everyone if the first frame is dropped.

> Last frame found is 3599, expected to end at 3600. Last frame number tolerance is 0.

The content finishes with a red last frame. The red frame at the end needs to be visible. That's why it's there.

But we currently have a known issue where the red and green frames don't have annotations and the red frame isn't included in the test stream. https://github.com/cta-wave/Test-Content/issues/12. This will require the mezzanine content to be re-generated.

> Mid frame number tolerance is 0. Frame 17 is missing.

Perhaps mid frame tolerance can be set to say 2?

**Comment by yanj-github** [comment]
Thanks @jpiesing so the best default values can be:
start_frame_num_tolerance = 0
end_frame_num_tolerance = 0
mid_frame_num_tolerance = 2

When mezzanine gets regenerated to include green and red frames OF required to be changed so that it checks these. 
Following: cta-wave/Test-Content#12

**Comment by yanj-github** [comment]
@jpiesing Are you happy about the default values to be changed to as follows please?
start_frame_num_tolerance = 0
end_frame_num_tolerance = 0
mid_frame_num_tolerance = 2

**Comment by jpiesing** [comment]
> @jpiesing Are you happy about the default values to be changed to as follows please?
> start_frame_num_tolerance = 0
> end_frame_num_tolerance = 0
> mid_frame_num_tolerance = 2

@yanj-github I suggest making mid_frame_num_tolerance 10 but leaving the other two as-is.

**Comment by yanj-github** [comment]
@jpiesing can you confirm that you happy with default values of thresholds, then I will close this issue.

**Comment by jpiesing** [comment]
OK.
