### ISSUE TITLE
debugging of 'frame nnn is missing'

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#24]
How are implementers supposed to debug failures due to 'frame nnn' is missing?

You can look at the video file & step through frame by frame to see if the frame is there but I'm not sure how much that helps.
Looking at C0026 which I sent @yanj-github earlier today, when I analyse this, a very large number of frames are missing.

Frame 401 is missing. Frame 412 is missing. Frame 413 is missing. Frame 416 is missing. Frame 417 is missing. Frame 424 is missing. Frame 425 is missing. Frame 428 is missing. Frame 429 is missing. Frame 436 is missing. Frame 437 is missing. Frame 440 is missing. Frame 441 is missing. Frame 444 is missing. Frame 445 is missing. Frame 531 is missing. 

Stepping through it frame by frame, it seems like 412, 413, 416 and 417 are present.

What next?

Since this is a 120Hz recording of 60hz content, each of 412, 413, 416 and 417 are spread across two frames. I think there needs to be a way ask the observation framework to dump out data extracted from the QR codes on each frame. It may be useful to have more than one level of debugging, e.g. level 1 just prints what mezzanine content frame number was extracted from the QR code on each captured frame & level 2 prints all the information.

Other debugging support may be useful too.

**Comment by yanj-github** [comment]
@jpiesing We can print the following information to a CSV file for each test and save it on the path “logs/<session_id>/<test>”.
The csv file contains mezzanine QR codes as well as the test status QR codes.

Please see the following example:
![qr_code_extraction](https://user-images.githubusercontent.com/59022223/121386844-2292c280-c942-11eb-9867-59a484029041.png)

Will it help please?

**Comment by jpiesing** [comment]
@yanj-github In principle that looks OK. Could you generate such a .CSV file for the C00026.MP4 file I sent you via wetransfer earlier this week so I can look at real problems?

**Comment by yanj-github** [comment]
@jpiesing Ok I will try squeeze in this for you hopfuly this week.

I managed to investigate the recording that you sent me.
Anf now I know where is the problem. 
By looking into the OF log:
_Content ID=L2 Media Time=6883.0 Frame Number=413 Frame Rate=60.0 Captured on Frame=4024
Content ID=L2 Media Time=6867.0 Frame Number=412 Frame Rate=60.0 Captured on Frame=4025_

The problem is OF sees the frames out of order so 413 is detected before the 412. 

This is because of the screen set too bright so that QR code is recognised when it is fading out instead of when it is in its full appearence. I have attached a screen shot below. I must say this is not really clear to human eyes, however you see the top left QR code for 412 has a tiny spread out on the edge. 
![image](https://user-images.githubusercontent.com/59022223/121509104-37bd2f00-c9de-11eb-9eb7-cfdda9233ac7.png)

You may want to adjust the DUT screen a little bit darker please?

**Comment by jpiesing** [comment]
> You may want to adjust the DUT screen a little bit darker please?

I can do that.
Can you make it generate a clear error message if frames are detected out of order?

**Comment by nicholas-fr** [comment]
@yanj-github I'd just like to make sure I've understood what the issue is.

Is the issue that 412 wasn't detected earlier due to the brightness, and consequently, 413 is detected before 412?
I would have expected frame 412 to have already been detected before the recording image you reference above. 
It's the 3rd in the sequence below, and the 412 QR code first appears 2 recording frames prior. I'd expect it to be detected in the 2nd image below (i.e. 1 recording frame earlier).

Or is the issue that 412 is detected _again_ for a 2nd time after 413? 
With display panels that have a slower response time, having 3 QR codes on screen will happen quite frequently with 60fps content. I assume this is already handled appropriately by the observation framework?

![image](https://user-images.githubusercontent.com/9865551/121566540-e896ee80-ca1d-11eb-9b16-196bb4e6e770.png)
![image](https://user-images.githubusercontent.com/9865551/121566443-d1f09780-ca1d-11eb-9408-815c26842b74.png) <- expect that 412 should be detected here
![image](https://user-images.githubusercontent.com/9865551/121566479-d9b03c00-ca1d-11eb-9197-27a44c5a2d71.png) <- this is the image you referenced
![image](https://user-images.githubusercontent.com/9865551/121566507-e0d74a00-ca1d-11eb-8a48-419a6f04890f.png)

**Comment by nicholas-fr** [comment]
I noticed you're using the ([pyzbar](https://github.com/NaturalHistoryMuseum/pyzbar)) package for QR code detection.

If the issue is that the QR codes aren't being detected, then maybe some of the parameters could be adjusted?
In a quick test I did, pyzbar was able to detect the QR codes listed in the opening comment, so I just wonder if something can be improved?

> Frame 401 is missing. Frame 412 is missing. Frame 413 is missing. Frame 416 is missing. Frame 417 is missing. Frame 424 is missing. Frame 425 is missing. Frame 428 is missing. Frame 429 is missing. Frame 436 is missing. Frame 437 is missing. Frame 440 is missing. Frame 441 is missing. Frame 444 is missing. Frame 445 is missing. Frame 531 is missing.

![image](https://user-images.githubusercontent.com/9865551/121572469-855c8a80-ca24-11eb-9cb3-df38c8f81d91.png)

**Comment by yanj-github** [comment]
Thanks @nicholas-fr we have two levels of thresholding but 2nd threshold not get called if one mezzanine QR code is found. I can make change to enable 2 levels of thresholding all the time, so that all the QR codes get picked up. Which I believe it will solve this problem.

However, the processing time now became much more longer. Thresholding imgae is long to process.
One test now taking about an hour to process on OF. Please note that we are adding print out every frame QR code information to CVS file as well which takes up some processing time as well. 

Is that fine with you please? @jpiesing

**Comment by jpiesing** [comment]
> However, the processing time now became much more longer. Thresholding imgae is long to process.

@nicholas-fr How long is the processing time per image in the test you did?

**Comment by yanj-github** [comment]
@jpiesing  I hvae done a rough measurement on my PC, it is about 150ms for one threshold and if we have 2 then 300ms each image. 
OF framework processing 10 frames take around 3.3 seconds.

**Comment by jpiesing** [comment]
@yanj-github Are you processing the whole image or just the areas which can contain the QR codes? How would the times scale if you limited the areas searched to those that can contain QR codes?

**Comment by yanj-github** [comment]
@jpiesing I am processing whole image. The QR code aear is almost colse to the full image as we have mezzanine QR code on the lest and test status QR code on the right. And pre-test QR code is in the middle. I would assume crop and porcess will take longer as it truns up as 3 different way to crop the image. 
![image](https://user-images.githubusercontent.com/59022223/121886159-fe9dfb00-cd0c-11eb-9c1a-95f56a2833e6.png)

**Comment by nicholas-fr** [comment]
The code I use includes no thresholding.
I did experiment with it initially (only with THRESH_BINARY), but pyzbar does such a good job, it didn't seem to help much. In fact, in some cases it made detection worse (but of course I may not have configured it very well in my limited experiments).

I was initially only processing part of the left area of each frame which takes ~55ms/frame:
![image](https://user-images.githubusercontent.com/9865551/121891078-56dbf980-cd1b-11eb-9ab0-99014127bd78.png)

Processing the whole image takes ~140ms/frame.
Running on a laptop with a i7 5600U CPU.

**Comment by jpiesing** [comment]
@yanj-github IMHO the project needs to be really, really robust when faced with marginal camera setups. If that slows down the time to run then so be it. 

It seems that you and Nicholas don't agree about whether thresholding is needed. Are you both using the same version of the library?

Can the library return the coordinates of the QR code that was extracted? If so then it would be possible to calibrate and exclude areas of the screen that will never have a QR code. Even excluding 30% is worth doing.

**Comment by nicholas-fr** [comment]
Regarding thresholding it may still be useful, only in my limited tests it seemed not to be. 
As my test script without thresholding was able to detect QR codes that the observation framework did not, it might be worth looking into.
I expect we're both using the latest pyzbar version (0.1.8).
The coordinates of detected QR codes are returned.

**Comment by yanj-github** [comment]
@nicholas-fr Thanks. Which range did you take for THRESH_BINARY? I used 127 to 255. The other differences is I processed full image.

**Comment by jpiesing** [comment]
A few thoughts ...

It should be possible to start checking the entire frame for QR codes and then once both the QR codes from the video & the QR codes from the app have been detected, reduce the checked area to that which is actually used in the real world.

I'm still puzzled why Nicolas's test script can successfully extract QR codes without needing thresholding when the OR fails on the same stream.

**Comment by nicholas-fr** [comment]
@yanj-github I experimented with a few different THRESH_BINARY ranges including 120-255, 140-255, 170-255, 190-255.

After running the same test script processing the full image instead of only part, I see detection is _less_ reliable.
In a video where some of the initial QR codes were a little blurry, 4 _fewer_ codes were detected when processing the full image as opposed to the specific QR code area. 

So performing QR code detection on specific parts of the video is something that can apparently be used to improve robustness.

**Comment by yanj-github** [comment]
I have added scans for just cropped qr code area, and here are the exported qr code list. 
@jpiesing  can you let us know if you are happy about the file format please? Just change .txt to .csv after you downloaded it. 
[qr_code_list.txt](https://github.com/cta-wave/device-observation-framework/files/6687913/qr_code_list.txt)

**Comment by yanj-github** [comment]
With adding scans for the cropped area of the qr codes make detection better Thanks @nicholas-fr  and @jpiesing.
Now we have made improvemnt and managed to reach similar robustness in detection that Nicolas has.

However there are still a small number of QR codes that are failed to get detected. We can do more improvement by adding adaptive threshold however it will add around 20mins per test to the processing time.

The other improvement is to make background of the QR code area to plain black so that when it fading in / out it wont get merged with actual video content. If mezzanine contnets get regenerated, it is an possible improvement to be added.

**Comment by jpiesing** [comment]
See https://github.com/cta-wave/mezzanine/issues/36 .

**Comment by nicholas-fr** [comment]
Regarding the remaining improvement, a test mezzanine stream was uploaded here to help investigate:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2021-07-19/tos_A1_480x270@30_60.mp4

**Comment by yanj-github** [comment]
Now we have csv file genetated in the log folder to help debugging. Feel free to close this issue when you happy with the fix please @jpiesing

**Comment by jpiesing** [comment]
Looks good.
