### ISSUE TITLE
New test content 2022-10-17

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/device-observation-framework#41]
The new test content is now available in the test runner. Checkout the branch 'dpcat-2022-10-17' in the dpctf-deploy repository and use `./build.sh --tests-branch dpcat-2022-10-17` when building the image

**Comment by FritzHeiden** [comment]
I changed to the new content while keeping the test logic the same, and verified all test run and terminate properly in chromium and firefox. I just pushed an update where I adjusted the test-config.json to the new test. 

@yanj-github Could you please verify the content works from your end with the observation framework?

**Comment by FritzHeiden** [comment]
> The new test content is now available in the test runner. Checkout the branch 'dpcat-2022-10-17' in the dpctf-deploy repository and use `./build.sh --tests-branch dpcat-2022-10-17` when building the image

@yanj-github I am sorry, of course you also have to specify the test-runner branch and tag: `./build.sh master latest --tests-branch dpcat-2022-10-17`. I just wanted to point out which branch to use for the tests

**Comment by FritzHeiden** [comment]
As I already mentioned, please use the branch `dpcat-2022-10-17` for dpctf-deploy and dpctf-tests. There are no changes in the test runner, just use `master`. For the content, there is no straight forward way to tell which version is present. In this version, you should see three `*v4.mpd` files in the content root.

To make sure you have the latest version, remove all docker images related to dpctf and rebuild with the specified parameters.

The commit ids can be seen in the corresponding repositories on github, here they are anyway:

- [`dpcat-2022-10-17`](https://github.com/cta-wave/dpctf-deploy/tree/dpcat-2022-10-17) branch in `dpctf-deploy`: `6f9af8f854e447d1e424a04eb80af24247f46e63`
- [`dpcat-2022-10-17`](https://github.com/cta-wave/dpctf-tests/tree/dpcat-2022-10-17) branch in `dpctf-tests`: `93e4a9b27c79a8404b72973e120f38ce77c783de`
- [`master`](https://github.com/cta-wave/dpctf-test-runner) branch in `dpctf-test-runner`: `0706c3f831ac0e99e97d9ab083c6c86cd20bba49`
- [`latest commit`](https://github.com/cta-wave/Test-Content/tree/6a363ca9225f41cc3f03d0bb286f99647f89d04b) in `Test-Content`: `6a363ca9225f41cc3f03d0bb286f99647f89d04b`

Looks like you've got the correct versions.

**Comment by yanj-github** [comment]
We are blocked on this until get further verifiaction report and results as requested https://github.com/cta-wave/dpctf-tests/issues/96#issuecomment-1351731122

**Comment by FritzHeiden** [comment]
Here are the test results from our run. Please rebuild the image before testing

[results-4a7ee3ee.zip](https://github.com/cta-wave/device-observation-framework/files/10393790/results-4a7ee3ee.zip)

**Comment by yanj-github** [comment]
Thanks @FritzHeiden for providing this, this is really helpful.

I have following two questions before we can start our validation if you can help, please?

1. We will rebuild the image; can you confirm that it was just dpctf-test has been changed and can you confirm the following please?
- dpctf-deploy: 6f9af8f854e447d1e424a04eb80af24247f46e63
- dpctf-test-runner: 0706c3f831ac0e99e97d9ab083c6c86cd20bba49
- **dpctf-tests: b0be150a4ecef3c49e35d6dbf3e903af7b17e7f0 (updated version)**
- test contents: 6a363ca9225f41cc3f03d0bb286f99647f89d04b

2. I would like to know which browser and devices have you tested these please? Can we assume unless stated that all tests have passed on both Chrome and Firefox? Or should/can we assume to only check against one of those if we see an issue? Note we intend to run the tests on a TV for this test run.

We can start our validation on dpctf tests, once we have information for the above two questions.

Note we do make the following assumptions when validating with the OF:
1. The correct media is presented for each test and they each contain the correct annotations.
2. Media fragments are presented correctly as required for the test or defined playout.
e. g: for random access it starts from accessing point.
3. Current time report and other status from test runner are correct.
4. Shared configurations are correctly defined.

In addition to this, there is an error for encrypted tests. We are not planning to test them if there is a fault already presented on test. However, this won’t block us because observation logic is same as sequential playback test.

Furthermore, we would like to validate the dpcat test OF capability but cannot see if the dpcat tests have been validated on the test runner? If not, could they be validated and when ready could the test report please be shared? If they have been validated, if that could please be confirmed and any testing results shared we would be very grateful.

**Comment by FritzHeiden** [comment]
> We can start our validation on dpctf tests, once we have information for the above two questions.

Can confirm 1. and 2., tested in chromium and firefox.

> In addition to this, there is an error for encrypted tests. We are not planning to test them if there is a fault already presented on test. However, this won’t block us because observation logic is same as sequential playback test.

What error do you have? Did you manually confirm the usage of the unsigned certificate?

> Furthermore, we would like to validate the dpcat test OF capability but cannot see if the dpcat tests have been validated on the test runner? If not, could they be validated and when ready could the test report please be shared? If they have been validated, if that could please be confirmed and any testing results shared we would be very grateful.

I don't really understand what you mean by that. Test reports of dpcat tests are included in the provided json files.

**Comment by FritzHeiden** [comment]
Here are the test results for firefox: 

[results-c076e388.json.zip](https://github.com/cta-wave/device-observation-framework/files/10427792/results-c076e388.json.zip)

**Comment by yanj-github** [comment]
> > In addition to this, there is an error for encrypted encrypted . We are not planning to test them if there is a fault already presented on test. However, this won’t block us because observation logic is same as sequential playback test.
> 
> What error do you have? Did you manually confirm the usage of the unsigned certificate?

I meat I can see from the result that you have shared "results-4a7ee3ee.zip" it shows error for the encrypted tests.
"status": "ERROR", 
"message": "Unhandled rejection: Failed to initialize session", 


> > Furthermore, we would like to validate the dpcat test OF capability but cannot see if the dpcat tests have been validated on the test runner? If not, could they be validated and when ready could the test report please be shared? If they have been validated, if that could please be confirmed and any testing results shared we would be very grateful.
> 
> I don't really understand what you mean by that. Test reports of dpcat tests are included in the provided json files.

regarding to DPCAT tests I meant the following tests, are they not ready please?

- buffer-underrun-and-recovery
- truncated-playback-and-restart
- low-latency-initialization
- low-latency-playback-over-gaps
- low-latency-short-buffer-playback
- random-access-from-one-place-in-a-stream-to-a-different-place-in-the-same-stream
- mse-appendwindow

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden  :) @yanj-github are you still blocked by anything?

**Comment by yanj-github** [comment]
> Thanks @FritzHeiden :) @yanj-github are you still blocked by anything?

Thanks @FritzHeiden and @louaybassbouss:

We can start with dpcat tests, ones they are tested and passed. 
The encrypted tests show error from your result.
However, this is fine on OF side as the observation logic is same as the general playback test, so we are not planning to test if it shows error already on test runner.

In terms of DPCAT we will wait until they are ready and tested on test runner before we can verify on our end.

**Comment by FritzHeiden** [comment]
Here are the missing dpcat results. Please rebuild to use the new dpctf-tests version.

[results-dpcat-local.zip](https://github.com/cta-wave/device-observation-framework/files/10436877/results-dpcat-local.zip)

As for the error in the cenc test, you can go ahead and test it as well. The error recorded by the test runner is not relevant for the test, I will have to add an exception for it.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden for sharing result of dpcat as well.
Can you confirm only **dpctf-tests: fa23b6a03e90fc3e6082cb88b96232bd52c297e3** is updated please?

**Comment by FritzHeiden** [comment]
> Can you confirm only **dpctf-tests: fa23b6a03e90fc3e6082cb88b96232bd52c297e3** is updated please?

Yes, can confirm.

**Comment by yanj-github** [comment]
Device observation framework is tested and verified, we have covered each test code at least once and covered each frame rate family at least once. You are going to merge the dpcat barnch to main in a week's time.
