### ISSUE TITLE
optimisation when analysing failures reported by OF - not re-running QR code detection

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#60]
When analysing failures reported by the OF, it would be really helpful if QR code detection was not re-run if there is a valid qr_code_list.csv file (valid = more recent than recording, recording has correct file size).

**Comment by pshorrock** [comment]
@jpiesing I have emailed separately with more detailed rationale but as a work-around to help make validation more efficient would the video content separated out to be test by test help (rather than one continuous file)? If so we have already done that for you and can share it back. As also mentioned in the email we do have some concerns adding in capability which might open up an ability to manually work around failures ("QR code detection was not re-run if there is a valid qr_code_list.csv file") where we see using output file can help to observe necessary tolerances. And can see in the other case opencv limiting the efficiency of stepping through a video file to get to a certain point, we think simply presenting a single video file to the OF which has only the test you are looking at included would be more efficient for the OF, and much quicker for us to help support you with today to help validation. @yanj-github @rcottingham can both help to follow up on this as needed. If we have misunderstood to reasons for the request (validation of the OF and test suite, not typical functionality required by users) we are happy to talk it through. And as part of that we do see dividing up content into separate files as a relatively easy task we'd be happy to document.

**Comment by jpiesing** [comment]
Closing as this is less relevant once we have agreed values for tolerances and thresholds.
