### ISSUE TITLE
timing issue between test and OF for TV 2 in buffer-underrun-and-recovery__t2

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#77]
TV 2 from the London plugfest fails buffer-underrun-and-recovery__t2 in the currentTime observation as follows;

![image](https://github.com/cta-wave/device-observation-framework/assets/8490792/2f48cd45-0b86-4b43-a4e6-3aea2a9d7ce3)

FAIL:  Allowed tolerance is 2 frames, 20ms. Time difference between Test Runner reported media currentTime and actual media time exceeded tolerance for following events: currentTime=0.04 time_diff=1.7976931348623157e+308;  Total failure count is 1.

As far as I remember, the e+308 issue is a timing issue or race condition between the OF and the test code where the latter has not provided information when the OF is expecting it.

@yanj-github Please can you work out what information is missing and then let's have a discussion with @FritzHeiden

**Comment by yanj-github** [comment]
@jpiesing I need to look at the recording to be sure but I guess this is due to "at the reported current Time = 0.04 there is no presented video sample". As we are checking "presented samples matching current Time" we could change OF to ignore current time reports where no matching presented video sample, rather than fail the test.

**Comment by yanj-github** [comment]
Fix is now committed the main.

**Comment by yanj-github** [comment]
@jpiesing can it be closed please? Current Time match test is now PASS for TV2.
